// Generated by CoffeeScript 1.7.1
(function() {
  var argv, greet, opts, parseArgs;

  greet = require("../lib/index.js");

  parseArgs = require("minimist");

  argv = parseArgs(process.argv, opts = {});

  console.log(greet(process.argv[2], argv.drunk));

  greet = require("../lib/index.js");

  module.exports = command;

}).call(this);
